### ISSUE TITLE
No such file or directory @ rb_sysopen - /tmp/rulp-812.sol (Errno::ENOENT)

### ISSUE THREAD

**Issue by jonahgeorge** [wouterken/rulp#4]
_I haven't gotten a chance to look further into this but I'll be digging into it over the weekend._

Figured I would just start a conversation to see if you already knew anything about this. There appears to be an interesting edge case where calling `#solve` fails due to the `.sol` file not being found. Unfortunately, I _have not_ been able to reduce this to a reproducible test. My initial thoughts are to the two separate definitions of `#get_output_filename` in `Problem` and `Solver`.

Below is the full dump if it helps.

``` sh
/Users/jonahgeorge/.gem/ruby/2.3.0/bundler/gems/rulp-89f4502d8c28/lib/solvers/cbc.rb:21:in `read': No such file or directory @ rb_sysopen - /tmp/rulp-736.sol (Errno::ENOENT)
    from /Users/jonahgeorge/.gem/ruby/2.3.0/bundler/gems/rulp-89f4502d8c28/lib/solvers/cbc.rb:21:in `store_results'
    from /Users/jonahgeorge/.gem/ruby/2.3.0/bundler/gems/rulp-89f4502d8c28/lib/rulp/rulp.rb:183:in `solve_with'
    from /Users/jonahgeorge/.gem/ruby/2.3.0/bundler/gems/rulp-89f4502d8c28/lib/rulp/rulp.rb:46:in `Cbc'
    from /Users/jonahgeorge/.gem/ruby/2.3.0/bundler/gems/rulp-89f4502d8c28/lib/rulp/rulp.rb:122:in `call'
    from /Users/jonahgeorge/.gem/ruby/2.3.0/bundler/gems/rulp-89f4502d8c28/lib/rulp/rulp.rb:113:in `method_missing'
    from /Users/jonahgeorge/Workspace/gta-assignment/lib/integer_linear_program.rb:29:in `solve'
    from lib/spring_ilp.rb:28:in `run'
    from lib/spring_ilp.rb:390:in `<top (required)>'
    from /Users/jonahgeorge/.gem/ruby/2.3.0/gems/railties-4.2.0/lib/rails/commands/runner.rb:60:in `load'
    from /Users/jonahgeorge/.gem/ruby/2.3.0/gems/railties-4.2.0/lib/rails/commands/runner.rb:60:in `<top (required)>'
    from /Users/jonahgeorge/.gem/ruby/2.3.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require'
    from /Users/jonahgeorge/.gem/ruby/2.3.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
    from /Users/jonahgeorge/.gem/ruby/2.3.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:90:in `runner'
    from /Users/jonahgeorge/.gem/ruby/2.3.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/jonahgeorge/.gem/ruby/2.3.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by wouterken** [comment]
Hi Jonah,

The lack of a solution file could be due to a number of reasons.
- Could it be your model was infeasible and CBC did not produce a solution?
- If you look at the source of `#get_output_filename` you'll see it's a lazy implementation relying mostly on luck! So not very robust. Picking a random number and hoping it is unique is not a good way to generate a filename and certainly something that needs to be replaced with a proper implementation. If you happen to be running two solves at once there's a chance they attempt to read or write from the same location and get in each others way.

The log of the CBC solver should give you a hint as to why there is not output file. That would be the first thing I inspect in this scenario.

Which version of Rulp are you using?

**Comment by jonahgeorge** [comment]
Alright, I feel bad for opening this before enabling logging. Completely forgot about that.

After enabling logging with CBC, I get this... the CoinError is not incredibly helpful

``` sh
D, [2016-05-27T14:51:44.437211 #62735] DEBUG -- : libc++abi.dylib: terminating with uncaught exception of type CoinError
D, [2016-05-27T14:51:44.437338 #62735] DEBUG -- : Welcome to the CBC MILP Solver 
D, [2016-05-27T14:51:44.437380 #62735] DEBUG -- : Version: 2.9.6 
D, [2016-05-27T14:51:44.437419 #62735] DEBUG -- : Build Date: Oct 20 2015 
D, [2016-05-27T14:51:44.437445 #62735] DEBUG -- : 
D, [2016-05-27T14:51:44.437476 #62735] DEBUG -- : command line - cbc /tmp/rulp-111.lp branch solution /tmp/rulp-48.sol (default strategy 1)
D, [2016-05-27T14:51:44.496129 #62735] DEBUG -- : Solver took 0.069851
I, [2016-05-27T14:51:44.496185 #62735]  INFO -- : Parsing result
```

Instead, I tried re-running the exact same program with GLPK and got this (a little better).

``` sh
D, [2016-05-27T14:55:28.667345 #63371] DEBUG -- : GLPSOL: GLPK LP/MIP Solver, v4.60
D, [2016-05-27T14:55:28.667436 #63371] DEBUG -- : Parameter(s) specified in the command line:
D, [2016-05-27T14:55:28.667485 #63371] DEBUG -- :  --lp /tmp/rulp-39.lp --cuts --output /tmp/rulp-589.sol
D, [2016-05-27T14:55:28.667524 #63371] DEBUG -- : Reading problem data from '/tmp/rulp-39.lp'...
D, [2016-05-27T14:55:28.671836 #63371] DEBUG -- : /tmp/rulp-39.lp:90: missing '<', '<=', or '=<' after lower bound
D, [2016-05-27T14:55:28.671914 #63371] DEBUG -- : CPLEX LP file processing error
D, [2016-05-27T14:55:28.672257 #63371] DEBUG -- : Solver took 0.010182
I, [2016-05-27T14:55:28.672296 #63371]  INFO -- : Parsing result
```

Relevant lines of the LP file:

``` lp
89: Bounds
90:  0.1 VAR19_1_is_assigned_to_section <= VAR19_1 <= 100000 VAR19_1_is_assigned_to_section
91:  0.1 VAR19_2_is_assigned_to_section <= VAR19_2 <= 100000 VAR19_2_is_assigned_to_section
```

Here's the ruby code that generates the bounds:

``` rb
def lower_bounds_constraint
  @students.each do |student|
    @sections.each do |section|
      # @problem[ VAR_f(student.id, section.id) == 0 ]
      # OR
      # @problem[ VAR_f(student.id, section.id) >= 0.10 ]
      #
      # "Big M Method"
      # https://en.wikipedia.org/wiki/Big_M_method
      # http://stackoverflow.com/questions/24449959/linear-programming-constraint-x-c-or-x-0
      # x_i >= c_i y_i
      # x_i <= M y_i
      @problem[ VAR_f(student.id, section.id) >=     0.10 * VAR_b(student.id, section.id, "is_assigned_to_section") ]
      @problem[ VAR_f(student.id, section.id) <=   100000 * VAR_b(student.id, section.id, "is_assigned_to_section") ]
    end
  end
end
```

**Comment by wouterken** [comment]
Hi Jonah,

Ah the first interesting thing I see there is that you have LP variables on both sides of your expressions. The LP file format seems to be quite restricted in that it needs all LP variables on the left of the comparison and constants on the right.

So while you can still use the constraints, you just have to express them slightly differently.
E.g 

``` ruby
VAR_f(student.id, section.id) >=     0.10 * VAR_b
```

becomes

```
VAR_f(student.id, section.id) - 0.10 * VAR_b >=  0
```

While making the Rulp library clever enough to translate the first example into the second will be a fun task unfortunately it isn't something I've done yet so you'll have to do it yourself.

Hope that gets you a bit further

**Comment by jonahgeorge** [comment]
That was super helpful, thank you again. 
Reading LP file spec also revealed the cause of some other smaller issues I've been having. 🎉
